---

 - name: Install Spotify Key
   apt_key:
     id: BBEBDCB318AD50EC6865090613B00F1FD2C19886
     keyserver: keyserver.ubuntu.com
     state: present

 - name: Install Spotify Repository
   apt_repository:
     repo: deb http://repository.spotify.com stable non-free
     state: present

 - name: Install Spotify
   apt: name=spotify-client state=installed