---
  - name: Add Adapta repository
    apt_repository: repo=ppa:tista/adapta

  - name: Install Adapta
    apt: name=adapta-gtk-theme state=installed

  - name: Add Papirus repository
    apt_repository: repo=ppa:papirus/papirus

  - name: Install papirus icon theme
    apt: name=papirus-icon-theme state=installed

  - name: Add Plank repository
    apt_repository: repo=ppa:docky-core/stable

  - name: Autostart Guake
    file:
      src: /usr/share/applications/plank.desktop
      dest: /home/{{user}}/.config/autostart/plank.desktop
      state: link
      owner: "{{user}}"

  - name: Install Plank
    apt: name=plank state=installed

  - name: Set Adapta Gtk theme
    command: gsettings set org.gnome.desktop.interface gtk-theme "Adapta-Nokto"
    become: "{{user}}"

  - name: Set Adapta Window theme
    command: gsettings set org.gnome.desktop.wm.preferences theme "Adapta-Nokto"
    become: "{{user}}"

  - name: Set Papirus icon theme
    command: gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
    become: "{{user}}"

  - name: Hide unity panel
    command: gsettings set org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/ launcher-hide-mode 1
    become: "{{user}}"

  - name: Create plank config
    file: path=/home/{{user}}/.config/plank/dock1/launchers state=directory owner={{user}}

  - name: Install Plank items
    template: src={{item}}.dockitem dest=/home/{{user}}/.config/plank/dock1/launchers owner={{user}} group={{user}} mode=0644
    with_items:
    - nautilus
    - spotify
    - trash
    - postman

  - name: Update Plank theme
    command: dconf write /net/launchpad/plank/docks/dock1/theme "'Transparent'"
    become: "{{user}}"

  - name: Update Plank items
    command: dconf write /net/launchpad/plank/docks/dock1/dock-items  "['nautilus.dockitem', 'firefox.dockitem', 'postman.dockitem', 'spotify.dockitem', 'cpumonitor.dockitem', 'clock.dockitem', 'trash.dockitem']"
    become: "{{user}}"

  - name: Remove default Plank items
    file:  path=/home/{{user}}/.config/plank/dock1/launchers/{{item}}.dockitem state=absent
    with_items:
    - eog
    - org.gnome.Calendar
    - org.gnome.Totem
    - rhythmbox